version: "3"

services:
  pocketwatcher:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "8090:8090"
    volumes:
      - pb_data:/pb/pb_data
    environment:
      - NEXT_PUBLIC_POCKETBASE_URL=http://localhost:8090

volumes:
  pb_data:
