services:
  pocketbase:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "8090:8090"
    volumes:
      - ./pocketbase/pb_data:/pb/pb_data
      - ./pocketbase/pb_hooks:/pb/pb_hooks
      - ./pocketbase/pb_migrations:/pb/pb_migrations
